"""add conversation_state table

Revision ID: dd7f62194fd8
Revises: add_crono_public_private_keys
Create Date: 2025-12-03 09:52:53.171100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd7f62194fd8'
down_revision: Union[str, None] = 'add_crono_public_private_keys'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state_key', sa.String(), nullable=False),
    sa.Column('state_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_states_state_key'), 'conversation_states', ['state_key'], unique=True)
    op.alter_column('user_settings', 'crono_api_key',
               existing_type=sa.VARCHAR(length=255),
               comment='DEPRECATED: Legacy combined Crono key (public/private)',
               existing_comment='API Key for Crono integration',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_settings', 'crono_api_key',
               existing_type=sa.VARCHAR(length=255),
               comment='API Key for Crono integration',
               existing_comment='DEPRECATED: Legacy combined Crono key (public/private)',
               existing_nullable=True)
    op.drop_index(op.f('ix_conversation_states_state_key'), table_name='conversation_states')
    op.drop_table('conversation_states')
    # ### end Alembic commands ###
