"""Add UserSettings table

Revision ID: 6a2601a43caf
Revises: 001_initial_schema
Create Date: 2025-11-30 20:31:49.217283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a2601a43caf'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID of the tenant (Slack workspace) this setting belongs to'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID of the user this setting belongs to'),
    sa.Column('crono_api_key', sa.String(length=255), nullable=True, comment='API Key for Crono integration'),
    sa.Column('fathom_api_key', sa.String(length=255), nullable=True, comment='API Key for Fathom integration'),
    sa.Column('piper_api_key', sa.String(length=255), nullable=True, comment='API Key for Piper.ai integration'),
    sa.Column('gmail_token', sa.Text(), nullable=True, comment='OAuth token for Gmail integration'),
    sa.Column('calendar_token', sa.Text(), nullable=True, comment='OAuth token for Calendar integration'),
    sa.Column('email_tone', sa.String(length=50), nullable=True, comment='Preferred tone for email drafts'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (NULL if active)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.alter_column('account_mappings', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Reference to tenant (Slack workspace)',
               existing_nullable=False)
    op.alter_column('account_mappings', 'crm_connection_id',
               existing_type=sa.UUID(),
               comment='CRM connection this mapping belongs to',
               existing_nullable=False)
    op.alter_column('account_mappings', 'email_domain',
               existing_type=sa.VARCHAR(length=255),
               comment='Email domain (e.g., neuronup.com)',
               existing_nullable=False)
    op.alter_column('account_mappings', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Company name for display',
               existing_nullable=True)
    op.alter_column('account_mappings', 'crm_account_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Account ID in CRM system',
               existing_nullable=False)
    op.alter_column('account_mappings', 'crm_account_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Account name in CRM system',
               existing_nullable=False)
    op.alter_column('account_mappings', 'mapping_source',
               existing_type=sa.VARCHAR(length=50),
               comment='Source: manual, auto_discovered, imported',
               existing_nullable=True)
    op.alter_column('account_mappings', 'confidence_score',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               comment='Confidence score 0.00-1.00 (for auto-discovered)',
               existing_nullable=True)
    op.alter_column('account_mappings', 'verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Whether mapping has been verified by user',
               existing_nullable=False)
    op.alter_column('account_mappings', 'times_used',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Number of times this mapping has been used',
               existing_nullable=False)
    op.alter_column('account_mappings', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last time this mapping was used',
               existing_nullable=True)
    op.alter_column('account_mappings', 'created_by_user_id',
               existing_type=sa.UUID(),
               comment='User who created this mapping',
               existing_nullable=True)
    op.alter_column('account_mappings', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier (UUID)',
               existing_nullable=False)
    op.alter_column('account_mappings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('account_mappings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('account_mappings', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was soft-deleted (NULL if active)',
               existing_nullable=True)
    op.create_index(op.f('ix_account_mappings_crm_connection_id'), 'account_mappings', ['crm_connection_id'], unique=False)
    op.create_index(op.f('ix_account_mappings_tenant_id'), 'account_mappings', ['tenant_id'], unique=False)
    op.alter_column('api_rate_limits', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Reference to tenant (Slack workspace)',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Resource being limited: meetings_processed, api_calls, crm_writes',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'limit_period',
               existing_type=sa.VARCHAR(length=20),
               comment='Time period: minute, hourly, daily, monthly',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'limit_value',
               existing_type=sa.INTEGER(),
               comment='Maximum allowed in period',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'current_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Current usage count in this period',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'period_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Start of the current period',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'period_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='End of the current period',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier (UUID)',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was soft-deleted (NULL if active)',
               existing_nullable=True)
    op.create_index(op.f('ix_api_rate_limits_tenant_id'), 'api_rate_limits', ['tenant_id'], unique=False)
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Reference to tenant (NULL for system events)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               comment='User who performed the action (NULL for system events)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Event type (e.g., crm.note.created, user.login)',
               existing_nullable=False)
    op.alter_column('audit_logs', 'event_category',
               existing_type=sa.VARCHAR(length=50),
               comment='Event category: authentication, data_access, configuration, integration, security',
               existing_nullable=False)
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type of resource affected (e.g., meeting_session, crm_connection)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.UUID(),
               comment='ID of the resource affected',
               existing_nullable=True)
    op.alter_column('audit_logs', 'action_description',
               existing_type=sa.TEXT(),
               comment='Human-readable description of the action',
               existing_nullable=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=postgresql.INET(),
               comment='IP address of the client',
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.TEXT(),
               comment='User agent string from client',
               existing_nullable=True)
    op.alter_column('audit_logs', 'request_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Sanitized request data (JSONB)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'response_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Sanitized response data (JSONB)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='Outcome: success, failure, partial',
               existing_nullable=False)
    op.alter_column('audit_logs', 'error_message',
               existing_type=sa.TEXT(),
               comment='Error message if status is failure',
               existing_nullable=True)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier (UUID)',
               existing_nullable=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('audit_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('audit_logs', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was soft-deleted (NULL if active)',
               existing_nullable=True)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.alter_column('crm_connections', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Reference to tenant (Slack workspace)',
               existing_nullable=False)
    op.alter_column('crm_connections', 'provider_type',
               existing_type=sa.VARCHAR(length=50),
               comment='CRM provider: crono, hubspot, salesforce, pipedrive',
               existing_nullable=False)
    op.alter_column('crm_connections', 'connection_name',
               existing_type=sa.VARCHAR(length=255),
               comment="User-friendly connection name (e.g., 'Production HubSpot')",
               existing_nullable=True)
    op.alter_column('crm_connections', 'credentials_secret_id',
               existing_type=sa.VARCHAR(length=255),
               comment='AWS Secrets Manager ARN/ID for credentials',
               existing_nullable=False)
    op.alter_column('crm_connections', 'oauth_access_token_secret_id',
               existing_type=sa.VARCHAR(length=255),
               comment='AWS Secrets Manager ID for OAuth access token',
               existing_nullable=True)
    op.alter_column('crm_connections', 'oauth_refresh_token_secret_id',
               existing_type=sa.VARCHAR(length=255),
               comment='AWS Secrets Manager ID for OAuth refresh token',
               existing_nullable=True)
    op.alter_column('crm_connections', 'oauth_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When OAuth access token expires',
               existing_nullable=True)
    op.alter_column('crm_connections', 'oauth_scopes',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment="OAuth scopes granted (e.g., ['crm.objects.contacts.read'])",
               existing_nullable=True)
    op.alter_column('crm_connections', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='Connection status: active, error, disconnected, refreshing',
               existing_nullable=False)
    op.alter_column('crm_connections', 'last_sync_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last successful sync with CRM',
               existing_nullable=True)
    op.alter_column('crm_connections', 'last_error',
               existing_type=sa.TEXT(),
               comment='Last error message encountered',
               existing_nullable=True)
    op.alter_column('crm_connections', 'last_error_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When last error occurred',
               existing_nullable=True)
    op.alter_column('crm_connections', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment='Provider-specific settings (JSONB)',
               existing_nullable=False)
    op.alter_column('crm_connections', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Whether this is the default CRM for the tenant',
               existing_nullable=False)
    op.alter_column('crm_connections', 'connected_by_user_id',
               existing_type=sa.UUID(),
               comment='User who created this connection',
               existing_nullable=True)
    op.alter_column('crm_connections', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier (UUID)',
               existing_nullable=False)
    op.alter_column('crm_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('crm_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('crm_connections', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was soft-deleted (NULL if active)',
               existing_nullable=True)
    op.create_index(op.f('ix_crm_connections_tenant_id'), 'crm_connections', ['tenant_id'], unique=False)
    op.alter_column('meeting_sessions', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Reference to tenant (Slack workspace)',
               existing_nullable=False)
    op.alter_column('meeting_sessions', 'user_id',
               existing_type=sa.UUID(),
               comment='User who initiated processing',
               existing_nullable=False)
    op.alter_column('meeting_sessions', 'fathom_recording_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Fathom recording ID',
               existing_nullable=False)
    op.alter_column('meeting_sessions', 'fathom_meeting_title',
               existing_type=sa.VARCHAR(length=500),
               comment='Meeting title from Fathom',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'fathom_meeting_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the meeting occurred',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'fathom_duration_minutes',
               existing_type=sa.INTEGER(),
               comment='Meeting duration in minutes',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'fathom_participants',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment='List of meeting participants',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'transcript_language',
               existing_type=sa.VARCHAR(length=10),
               comment='Detected language of transcript (e.g., en, it, es)',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'ai_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Structured AI summary output (JSONB)',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'email_draft',
               existing_type=sa.TEXT(),
               comment='Generated follow-up email draft',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'sales_insights',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Sales insights from AI analysis (JSONB)',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'crm_connection_id',
               existing_type=sa.UUID(),
               comment='CRM connection used for this session',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'crm_account_id',
               existing_type=sa.VARCHAR(length=255),
               comment='CRM account ID where data was stored',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'crm_account_name',
               existing_type=sa.VARCHAR(length=255),
               comment='CRM account name',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'crm_note_id',
               existing_type=sa.VARCHAR(length=255),
               comment='ID of created note in CRM',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'crm_deal_ids',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment='Associated deal IDs in CRM',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'gmail_draft_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Gmail draft ID',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'calendar_event_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Google Calendar event ID',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'calendar_event_link',
               existing_type=sa.TEXT(),
               comment='Link to calendar event',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'processing_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='Processing status: pending, processing, completed, failed, cancelled',
               existing_nullable=False)
    op.alter_column('meeting_sessions', 'processing_started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When processing started',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'processing_completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When processing completed',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'processing_error',
               existing_type=sa.TEXT(),
               comment='Error message if processing failed',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'actions_performed',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment="List of actions performed (e.g., ['email_draft', 'crm_note'])",
               existing_nullable=False)
    op.alter_column('meeting_sessions', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier (UUID)',
               existing_nullable=False)
    op.alter_column('meeting_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('meeting_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('meeting_sessions', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was soft-deleted (NULL if active)',
               existing_nullable=True)
    op.create_index(op.f('ix_meeting_sessions_tenant_id'), 'meeting_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_meeting_sessions_user_id'), 'meeting_sessions', ['user_id'], unique=False)
    op.alter_column('tenants', 'slack_team_id',
               existing_type=sa.VARCHAR(length=20),
               comment='Slack Team ID (e.g., T0123456789)',
               existing_nullable=False)
    op.alter_column('tenants', 'slack_team_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Workspace display name',
               existing_nullable=False)
    op.alter_column('tenants', 'slack_team_domain',
               existing_type=sa.VARCHAR(length=255),
               comment='Workspace domain (e.g., mycompany.slack.com)',
               existing_nullable=True)
    op.alter_column('tenants', 'plan_tier',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='Subscription plan: free, starter, pro, enterprise',
               existing_nullable=False)
    op.alter_column('tenants', 'subscription_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='Subscription status: active, trial, suspended, cancelled',
               existing_nullable=True)
    op.alter_column('tenants', 'trial_ends_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When trial period ends (if applicable)',
               existing_nullable=True)
    op.alter_column('tenants', 'slack_bot_token_secret_id',
               existing_type=sa.VARCHAR(length=255),
               comment='AWS Secrets Manager ID for bot token',
               existing_nullable=True)
    op.alter_column('tenants', 'slack_app_id',
               existing_type=sa.VARCHAR(length=20),
               comment='Slack App ID',
               existing_nullable=True)
    op.alter_column('tenants', 'installed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='When the app was installed',
               existing_nullable=False)
    op.alter_column('tenants', 'installed_by_user_id',
               existing_type=sa.VARCHAR(length=20),
               comment='Slack user ID who installed the app',
               existing_nullable=True)
    op.alter_column('tenants', 'default_crm_provider',
               existing_type=sa.VARCHAR(length=50),
               comment='Default CRM provider: crono, hubspot, salesforce, pipedrive',
               existing_nullable=True)
    op.alter_column('tenants', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='Workspace timezone',
               existing_nullable=False)
    op.alter_column('tenants', 'locale',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               comment='Workspace locale (language)',
               existing_nullable=False)
    op.alter_column('tenants', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier (UUID)',
               existing_nullable=False)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('tenants', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was soft-deleted (NULL if active)',
               existing_nullable=True)
    op.drop_index('idx_tenants_slack_team_id', table_name='tenants')
    op.drop_constraint('tenants_slack_team_id_key', 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_slack_team_id'), 'tenants', ['slack_team_id'], unique=True)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Reference to tenant (Slack workspace)',
               existing_nullable=False)
    op.alter_column('users', 'slack_user_id',
               existing_type=sa.VARCHAR(length=20),
               comment='Slack User ID (e.g., U0123456789)',
               existing_nullable=False)
    op.alter_column('users', 'slack_username',
               existing_type=sa.VARCHAR(length=255),
               comment='Slack username (display name)',
               existing_nullable=True)
    op.alter_column('users', 'slack_email',
               existing_type=sa.VARCHAR(length=255),
               comment='Slack user email address',
               existing_nullable=True)
    op.alter_column('users', 'slack_real_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Slack user real name',
               existing_nullable=True)
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               comment="User's preferred language (e.g., en, it, es)",
               existing_nullable=False)
    op.alter_column('users', 'notification_settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment='User notification preferences (JSONB)',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='User role: admin, member',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Whether user is active in workspace',
               existing_nullable=False)
    op.alter_column('users', 'first_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='When user first interacted with the bot',
               existing_nullable=False)
    op.alter_column('users', 'last_active_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When user last interacted with the bot',
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier (UUID)',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was soft-deleted (NULL if active)',
               existing_nullable=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted (NULL if active)',
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier (UUID)',
               existing_nullable=False)
    op.alter_column('users', 'last_active_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When user last interacted with the bot',
               existing_nullable=True)
    op.alter_column('users', 'first_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='When user first interacted with the bot',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='Whether user is active in workspace',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'member'::character varying"),
               comment=None,
               existing_comment='User role: admin, member',
               existing_nullable=False)
    op.alter_column('users', 'notification_settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text('\'{"email_drafts": true, "calendar_events": true}\'::jsonb'),
               comment=None,
               existing_comment='User notification preferences (JSONB)',
               existing_nullable=False)
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'en'::character varying"),
               comment=None,
               existing_comment="User's preferred language (e.g., en, it, es)",
               existing_nullable=False)
    op.alter_column('users', 'slack_real_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Slack user real name',
               existing_nullable=True)
    op.alter_column('users', 'slack_email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Slack user email address',
               existing_nullable=True)
    op.alter_column('users', 'slack_username',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Slack username (display name)',
               existing_nullable=True)
    op.alter_column('users', 'slack_user_id',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Slack User ID (e.g., U0123456789)',
               existing_nullable=False)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to tenant (Slack workspace)',
               existing_nullable=False)
    op.drop_index(op.f('ix_tenants_slack_team_id'), table_name='tenants')
    op.create_unique_constraint('tenants_slack_team_id_key', 'tenants', ['slack_team_id'])
    op.create_index('idx_tenants_slack_team_id', 'tenants', ['slack_team_id'], unique=False)
    op.alter_column('tenants', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted (NULL if active)',
               existing_nullable=True)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('tenants', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier (UUID)',
               existing_nullable=False)
    op.alter_column('tenants', 'locale',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'en'::character varying"),
               comment=None,
               existing_comment='Workspace locale (language)',
               existing_nullable=False)
    op.alter_column('tenants', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'UTC'::character varying"),
               comment=None,
               existing_comment='Workspace timezone',
               existing_nullable=False)
    op.alter_column('tenants', 'default_crm_provider',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Default CRM provider: crono, hubspot, salesforce, pipedrive',
               existing_nullable=True)
    op.alter_column('tenants', 'installed_by_user_id',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Slack user ID who installed the app',
               existing_nullable=True)
    op.alter_column('tenants', 'installed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='When the app was installed',
               existing_nullable=False)
    op.alter_column('tenants', 'slack_app_id',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Slack App ID',
               existing_nullable=True)
    op.alter_column('tenants', 'slack_bot_token_secret_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='AWS Secrets Manager ID for bot token',
               existing_nullable=True)
    op.alter_column('tenants', 'trial_ends_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When trial period ends (if applicable)',
               existing_nullable=True)
    op.alter_column('tenants', 'subscription_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'active'::character varying"),
               comment=None,
               existing_comment='Subscription status: active, trial, suspended, cancelled',
               existing_nullable=True)
    op.alter_column('tenants', 'plan_tier',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'free'::character varying"),
               comment=None,
               existing_comment='Subscription plan: free, starter, pro, enterprise',
               existing_nullable=False)
    op.alter_column('tenants', 'slack_team_domain',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Workspace domain (e.g., mycompany.slack.com)',
               existing_nullable=True)
    op.alter_column('tenants', 'slack_team_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Workspace display name',
               existing_nullable=False)
    op.alter_column('tenants', 'slack_team_id',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Slack Team ID (e.g., T0123456789)',
               existing_nullable=False)
    op.drop_index(op.f('ix_meeting_sessions_user_id'), table_name='meeting_sessions')
    op.drop_index(op.f('ix_meeting_sessions_tenant_id'), table_name='meeting_sessions')
    op.alter_column('meeting_sessions', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted (NULL if active)',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('meeting_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('meeting_sessions', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier (UUID)',
               existing_nullable=False)
    op.alter_column('meeting_sessions', 'actions_performed',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               comment=None,
               existing_comment="List of actions performed (e.g., ['email_draft', 'crm_note'])",
               existing_nullable=False)
    op.alter_column('meeting_sessions', 'processing_error',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Error message if processing failed',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'processing_completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When processing completed',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'processing_started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When processing started',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'processing_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'::character varying"),
               comment=None,
               existing_comment='Processing status: pending, processing, completed, failed, cancelled',
               existing_nullable=False)
    op.alter_column('meeting_sessions', 'calendar_event_link',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Link to calendar event',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'calendar_event_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Google Calendar event ID',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'gmail_draft_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Gmail draft ID',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'crm_deal_ids',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment=None,
               existing_comment='Associated deal IDs in CRM',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'crm_note_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='ID of created note in CRM',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'crm_account_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='CRM account name',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'crm_account_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='CRM account ID where data was stored',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'crm_connection_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='CRM connection used for this session',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'sales_insights',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Sales insights from AI analysis (JSONB)',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'email_draft',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Generated follow-up email draft',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'ai_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Structured AI summary output (JSONB)',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'transcript_language',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Detected language of transcript (e.g., en, it, es)',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'fathom_participants',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment=None,
               existing_comment='List of meeting participants',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'fathom_duration_minutes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Meeting duration in minutes',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'fathom_meeting_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the meeting occurred',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'fathom_meeting_title',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Meeting title from Fathom',
               existing_nullable=True)
    op.alter_column('meeting_sessions', 'fathom_recording_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Fathom recording ID',
               existing_nullable=False)
    op.alter_column('meeting_sessions', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who initiated processing',
               existing_nullable=False)
    op.alter_column('meeting_sessions', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to tenant (Slack workspace)',
               existing_nullable=False)
    op.drop_index(op.f('ix_crm_connections_tenant_id'), table_name='crm_connections')
    op.alter_column('crm_connections', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted (NULL if active)',
               existing_nullable=True)
    op.alter_column('crm_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('crm_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('crm_connections', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier (UUID)',
               existing_nullable=False)
    op.alter_column('crm_connections', 'connected_by_user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who created this connection',
               existing_nullable=True)
    op.alter_column('crm_connections', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Whether this is the default CRM for the tenant',
               existing_nullable=False)
    op.alter_column('crm_connections', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment=None,
               existing_comment='Provider-specific settings (JSONB)',
               existing_nullable=False)
    op.alter_column('crm_connections', 'last_error_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When last error occurred',
               existing_nullable=True)
    op.alter_column('crm_connections', 'last_error',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Last error message encountered',
               existing_nullable=True)
    op.alter_column('crm_connections', 'last_sync_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last successful sync with CRM',
               existing_nullable=True)
    op.alter_column('crm_connections', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'active'::character varying"),
               comment=None,
               existing_comment='Connection status: active, error, disconnected, refreshing',
               existing_nullable=False)
    op.alter_column('crm_connections', 'oauth_scopes',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment=None,
               existing_comment="OAuth scopes granted (e.g., ['crm.objects.contacts.read'])",
               existing_nullable=True)
    op.alter_column('crm_connections', 'oauth_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When OAuth access token expires',
               existing_nullable=True)
    op.alter_column('crm_connections', 'oauth_refresh_token_secret_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='AWS Secrets Manager ID for OAuth refresh token',
               existing_nullable=True)
    op.alter_column('crm_connections', 'oauth_access_token_secret_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='AWS Secrets Manager ID for OAuth access token',
               existing_nullable=True)
    op.alter_column('crm_connections', 'credentials_secret_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='AWS Secrets Manager ARN/ID for credentials',
               existing_nullable=False)
    op.alter_column('crm_connections', 'connection_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="User-friendly connection name (e.g., 'Production HubSpot')",
               existing_nullable=True)
    op.alter_column('crm_connections', 'provider_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='CRM provider: crono, hubspot, salesforce, pipedrive',
               existing_nullable=False)
    op.alter_column('crm_connections', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to tenant (Slack workspace)',
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.alter_column('audit_logs', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted (NULL if active)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier (UUID)',
               existing_nullable=False)
    op.alter_column('audit_logs', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Error message if status is failure',
               existing_nullable=True)
    op.alter_column('audit_logs', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Outcome: success, failure, partial',
               existing_nullable=False)
    op.alter_column('audit_logs', 'response_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Sanitized response data (JSONB)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'request_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Sanitized request data (JSONB)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='User agent string from client',
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=postgresql.INET(),
               comment=None,
               existing_comment='IP address of the client',
               existing_nullable=True)
    op.alter_column('audit_logs', 'action_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Human-readable description of the action',
               existing_nullable=False)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID of the resource affected',
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Type of resource affected (e.g., meeting_session, crm_connection)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'event_category',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Event category: authentication, data_access, configuration, integration, security',
               existing_nullable=False)
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Event type (e.g., crm.note.created, user.login)',
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who performed the action (NULL for system events)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to tenant (NULL for system events)',
               existing_nullable=True)
    op.drop_index(op.f('ix_api_rate_limits_tenant_id'), table_name='api_rate_limits')
    op.alter_column('api_rate_limits', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted (NULL if active)',
               existing_nullable=True)
    op.alter_column('api_rate_limits', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier (UUID)',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'period_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='End of the current period',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'period_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Start of the current period',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'current_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='Current usage count in this period',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'limit_value',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Maximum allowed in period',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'limit_period',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Time period: minute, hourly, daily, monthly',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Resource being limited: meetings_processed, api_calls, crm_writes',
               existing_nullable=False)
    op.alter_column('api_rate_limits', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to tenant (Slack workspace)',
               existing_nullable=False)
    op.drop_index(op.f('ix_account_mappings_tenant_id'), table_name='account_mappings')
    op.drop_index(op.f('ix_account_mappings_crm_connection_id'), table_name='account_mappings')
    op.alter_column('account_mappings', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted (NULL if active)',
               existing_nullable=True)
    op.alter_column('account_mappings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('account_mappings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('account_mappings', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier (UUID)',
               existing_nullable=False)
    op.alter_column('account_mappings', 'created_by_user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who created this mapping',
               existing_nullable=True)
    op.alter_column('account_mappings', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last time this mapping was used',
               existing_nullable=True)
    op.alter_column('account_mappings', 'times_used',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='Number of times this mapping has been used',
               existing_nullable=False)
    op.alter_column('account_mappings', 'verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Whether mapping has been verified by user',
               existing_nullable=False)
    op.alter_column('account_mappings', 'confidence_score',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               comment=None,
               existing_comment='Confidence score 0.00-1.00 (for auto-discovered)',
               existing_nullable=True)
    op.alter_column('account_mappings', 'mapping_source',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Source: manual, auto_discovered, imported',
               existing_nullable=True)
    op.alter_column('account_mappings', 'crm_account_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Account name in CRM system',
               existing_nullable=False)
    op.alter_column('account_mappings', 'crm_account_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Account ID in CRM system',
               existing_nullable=False)
    op.alter_column('account_mappings', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Company name for display',
               existing_nullable=True)
    op.alter_column('account_mappings', 'email_domain',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email domain (e.g., neuronup.com)',
               existing_nullable=False)
    op.alter_column('account_mappings', 'crm_connection_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='CRM connection this mapping belongs to',
               existing_nullable=False)
    op.alter_column('account_mappings', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to tenant (Slack workspace)',
               existing_nullable=False)
    op.drop_table('user_settings')
    # ### end Alembic commands ###
