#!/usr/bin/env python3
"""
Configuration Setup Helper
Helps you set up your API keys for the meeting follow-up system
"""

import os
import sys


def setup_env_file():
    """Interactive setup for .env file"""
    print("🔧 Meeting Follow-up Email Generator - Configuration Setup")
    print("=" * 60)
    print("\nThis script will help you configure your API keys.")
    print("You can get these keys from:")
    print("  • Anthropic API: https://console.anthropic.com/")
    print("  • Gemini API: https://makersuite.google.com/app/apikey")
    print("  • Fathom API: https://app.fathom.video/settings/integrations")
    print("\n" + "=" * 60)

    # Check if .env already exists
    if os.path.exists('.env'):
        overwrite = input("\n⚠️  .env file already exists. Overwrite? (yes/no): ")
        if overwrite.lower() not in ['yes', 'y']:
            print("Setup cancelled.")
            sys.exit(0)

    # Collect API keys
    print("\nEnter your API keys (press Enter to skip any):\n")

    anthropic_key = input("Anthropic (Claude) API Key: ").strip()
    gemini_key = input("Gemini API Key: ").strip()
    fathom_key = input("Fathom API Key: ").strip()

    # Write to .env file
    with open('.env', 'w') as f:
        f.write("# API Keys for Meeting Follow-up Generator\n")
        f.write("# Generated by setup_config.py\n\n")

        if anthropic_key:
            f.write(f"ANTHROPIC_API_KEY={anthropic_key}\n")
        else:
            f.write("# ANTHROPIC_API_KEY=your_key_here\n")

        if gemini_key:
            f.write(f"GEMINI_API_KEY={gemini_key}\n")
        else:
            f.write("# GEMINI_API_KEY=your_key_here\n")

        if fathom_key:
            f.write(f"FATHOM_API_KEY={fathom_key}\n")
        else:
            f.write("# FATHOM_API_KEY=your_key_here\n")

    print("\n✅ Configuration saved to .env file!")

    # Gmail setup reminder
    print("\n📧 Gmail API Setup")
    print("=" * 60)
    print("For Gmail integration, you also need to:")
    print("1. Go to: https://console.cloud.google.com/")
    print("2. Create a new project (or select existing)")
    print("3. Enable Gmail API")
    print("4. Create OAuth 2.0 credentials")
    print("5. Download credentials and save as 'credentials.json'")
    print("\nDetailed instructions in README.md")

    if not os.path.exists('credentials.json'):
        print("\n⚠️  credentials.json not found")
        print("   You'll need this file to use Gmail integration")
    else:
        print("\n✓ credentials.json found!")

    print("\n🎉 Setup complete! You can now run:")
    print("   python meeting_followup.py")
    print("\n" + "=" * 60)


if __name__ == "__main__":
    try:
        setup_env_file()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)
